"""empty message

Revision ID: 852e8e7b27ae
Revises: f787e2fd978f
Create Date: 2023-02-04 23:31:08.226016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852e8e7b27ae'
down_revision = 'f787e2fd978f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('num_of_members', sa.Integer(), nullable=True))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('num_of_members')
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
